name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          default: true

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: buildCachev25

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Prep
        run: |
          npm install -g pkg typescript @napi-rs/cli

      - name: Build Rust code
        run: |
          cd rust
          yarn
          yarn build
          cd ../
          copy ./rust/index.d.ts ./src/smf-rust.d.ts
          copy ./rust/rust.win32-x64-msvc.node ./src/smf-rust.node

      - name: Build EXE
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          New-Item -ItemType Directory -Force -Path ./node_modules/piscina
          robocopy ./piscina ./node_modules/piscina /E /is /it; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          tsc
          copy ./src/smf-rust.node ./compiled/smf-rust.node
          pkg package.json --targets node18-win-x64 --output Deploy.exe --compress Brotli

      - name: Ready for zip
        run: |
          New-Item -ItemType Directory dist
          copy Deploy.exe dist

      - name: Zip
        uses: TheDoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d
        with:
          filename: Release.zip
          directory: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.33.7
          files: dist/Release.zip